# render.yaml

services:
  # A PostgreSQL database
  - type: pserv
    name: tcc-portfolio-db
    plan: free
    # CORRECTED a
    postgresMajorVersion: 16
    ipAllowList: [] # Required for free instances

  # A Web Service for our Django App
  - type: web
    name: tcc-portfolio-app
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn TonyTheCoderPortfolio.wsgi"
    healthCheckPath: "/"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tcc-portfolio-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.12.3"
      - key: DJANGO_DEBUG
        value: "False"