# render.yaml

# This top-level key is specifically for database instances.
databases:
  - name: tcc-portfolio-db # This is the name for your database service
    plan: free # Use the free instance type
    postgresMajorVersion: 14

# The 'services' key is now only for your web application.
services:
  - type: web
    name: tcc-portfolio-app
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    # CHANGED: Use explicit python -m gunicorn and full WSGI application path
    startCommand: "python -m gunicorn TonyTheCoderPortfolio.wsgi:application"
    healthCheckPath: "/"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tcc-portfolio-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.12.3"
      - key: DJANGO_DEBUG
        value: "True"