# Generated by Django 5.2 on 2025-06-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_certificate_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AddField(
            model_name='certificate',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Controls if this certificate is visible on the public site.'),
        ),
    ]
