# Generated by Django 5.2 on 2025-06-12 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_delete_project_certificate_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='portfoliocategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='portfolioproject',
            name='is_active',
        ),
    ]
