# Generated by Django 5.2 on 2025-06-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_remove_certificate_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Controls if this project is visible on your public portfolio.'),
        ),
    ]
